### ISSUE TITLE
Merge GB18030-2022 patch from upstream

### ISSUE THREAD

**Issue by fundawang** [dragonwell-project/dragonwell8#563]
https://github.com/openjdk/jdk8u/commit/9740c2434fa39a6fac800e87160af659f718362c
https://github.com/openjdk/jdk8u/commit/3d9e8d05e053613afea1f4493121b5975a37ab2a

GB18030-2022即将于2023年8月1日强制执行，请尽快合入此补丁并发布新版本。

**Comment by linade** [comment]
已经merge上游, 等待发布
