### ISSUE TITLE
[Bug][Dragonwell Extended Edition 8.16.17]jck8d测试PackageTests未抛出IllegalArgumentException异常

### ISSUE THREAD

**Issue by sendaoYan** [dragonwell-project/dragonwell8#598]
**Description**
jck8d测试PackageTests未抛出IllegalArgumentException异常

**Steps to Reproduce**
java -Xfuture -classpath /home/yansendao/jck/jck8d/JCK-runtime-8d/classes javasoft.sqe.tests.api.java.lang.ClassLoader.PackageTests -TestCaseID ALL

**Expected behavior**
8.15.16版本用例PASS：
![image](https://github.com/dragonwell-project/dragonwell8/assets/24123821/b2f5556f-0def-4aa5-94e9-e0b651a20d54)

实际结果：
![image](https://github.com/dragonwell-project/dragonwell8/assets/24123821/7cf0afdb-0b3e-4b3d-a856-3551ebc22c8f)

**JDK version**
![image](https://github.com/dragonwell-project/dragonwell8/assets/24123821/327daf29-29e6-4bfd-acaf-889128761635)

**Comment by sendaoYan** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52814218# 《[Dragonwell Extended Edition 8.16.17]jck8d测试PackageTests未抛出IllegalArgumentException异常》

**Comment by sendaoYan** [comment]
![image](https://github.com/dragonwell-project/dragonwell8/assets/24123821/3f074f70-763e-4c5e-8066-948cc933cd07)

**Comment by Bughue** [comment]
https://aone.alibaba-inc.com/v2/project/355606/bug/52814218#

**Comment by jia-wei-tang** [comment]
> Hi, I'm currently unable to access the webpage [[Dragonwell Extended Edition 8.16.17]jck8d测试PackageTests未抛出IllegalArgumentException异常](https://aone.alibaba-inc.com/v2/project/355606/bug/52814218#) containing the specific test case details. Could you please advise how I might view these test cases through alternative means?
> 
> For context:
> 
> * I'm using JDK8_832 in my current environment
> * I'm planning to migrate to Dragonwell JDK
> * I need to understand how this issue might affect my codebase after the JDK transition
> 
> Specifically, I'd like to know:
> 
> 1. Where can I find the detailed test case information mentioned in this issue?
> 2. How should I evaluate the potential impact of this issue on my application?
> 3. Are there any known compatibility considerations between JDK8_832 and Dragonwell that relate to this particular case?
> 
> Any guidance or documentation you could provide would be greatly appreciated as I assess the migration risks.

I find the issue description for you.

**Description**
jck8d测试PackageTests未抛出IllegalArgumentException异常
**Steps to Reproduce** 
java -Xfuture -classpath /home/yansendao/jck/jck8d/JCK-runtime-8d/classes javasoft.sqe.tests.api.java.lang.ClassLoader.PackageTests -TestCaseID ALL
