### ISSUE TITLE
ARM弱内存一致性环境下，并发锁内部持有者更新异常，导致GC HANGE住的问题

### ISSUE THREAD

**Issue by wuqian0808** [dragonwell-project/dragonwell8#647]
相关OPENJDK BUG: https://bugs.openjdk.org/browse/JDK-8323913
相关修改之一 https://github.com/openjdk/jdk9/commit/7e084fd81fc5ef3e8245dc2381d4f13c016746c5
该问题OPENJDK9 及 毕昇JDK8已经修复
希望龙井JDK也尽快修复
谢谢！

**Comment by lingjun-cg** [comment]
好的,我们这边会尽快修复。

**Comment by wuqian0808** [comment]
@lingjun-cg 请问这个修复计划的发版时间是？或者龙井这边的发版节奏是?

**Comment by lingjun-cg** [comment]
每3个月

**Comment by sendaoYan** [comment]
> @lingjun-cg 请问下这个issue发版了吗，预计啥时候发版哈

版本已经发布 https://dragonwell-jdk.io/#/index

**Comment by lingjun-cg** [comment]
> @lingjun-cg 请问下这个issue发版了吗，预计啥时候发版哈

已经发布了，在https://dragonwell-jdk.io/#/index，8.20.21

**Comment by Nachtflug** [comment]
请问标准版本是否有集成

**Comment by lingjun-cg** [comment]
> 请问标准版本是否有集成

没有。标准版本是与上游保持一致的版本。

**Comment by sanhong** [comment]
建议你们可以使用 Extended版本。
