### ISSUE TITLE
[Build] Build result differences

### ISSUE THREAD

**Issue by RaymondLam1** [dragonwell-project/dragonwell8#708]
**Description**
I use dragonwell8 latest version [dragonwell-standard-8.23.22_jdk8u432-ga]( https://github.com/dragonwell-project/dragonwell8/releases/tag/dragonwell-standard-8.23.22_jdk8u432-ga) (linux x64). It's OK. However, I try to build myself dragonwell-standard-8.23.22 by Github Actions, and I get j2sdk-image. I tried running the same code, I got error: 
```
Error: dl failure on line 894
Error: failed /tmp/j2sdk-image/jre/lib/amd64/server/libjvm.so, because /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/j2sdk-image/jre/lib/amd64/server/libjvm.so)
```

**Expected behavior**
Are there any special techniques for the official version of the hairstyle?

**JDK version**
dragonwell-standard-8.23.22

**Comment by sendaoYan** [comment]
你的本地运行环境，跟编译环境的glibc版本不匹配导致的。你的编译环境glibc版本2.29，但是你的本地环境glibc版本低于2.29. 可以通过ldd --version命令查看运行环境的glibc版本

```
ldd --version
ldd (GNU libc) 2.32
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

**Comment by RaymondLam1** [comment]
> 你的本地运行环境，跟编译环境的glibc版本不匹配导致的。你的编译环境glibc版本2.29，但是你的本地环境glibc版本低于2.29. 可以通过ldd --version命令查看运行环境的glibc版本。需要你把运行环境换成glibc高于或等于2.29的环境上才能跑起来，比如alinux3、ubuntu22等

非常感谢你的回复。我很好奇，dragonwell 官方在发布新版本时是如何构建的呢？因为我使用官方的 JDK 是能在我的机器上正常运行，这说明是兼容低版本的 glibc 的。然而我通过 workflow 生成的 JDK 是不行的（因为 workflow 是在 ubuntu 20.04 版本构建的）。我希望能像官方一样构建出“非常棒的”JDK :)

**Comment by RaymondLam1** [comment]
我猜测官方在发布新版本（linux）时没有使用 workflow 的 ubuntu 20.04 环境，是否可以指导下如何发布新版本的呢？（仅用于排查问题，加了些代码，没有商用/开源想法）。

期待您的回复。

**Comment by sendaoYan** [comment]
`docker pull centos:7` 然后启动docker容器，在docker容器里安装构建依赖之后启动构建

**Comment by RaymondLam1** [comment]
> `docker pull centos:7` 然后启动docker容器，在docker容器里安装构建依赖之后启动构建

感谢回复~。
